### ISSUE TITLE
Problem with Rukuli::App#window ?

### ISSUE THREAD

**Issue by jrab89** [ndrluis/Rukuli#21]
Hi,

I'm trying to use Rukuli on Windows and I'm getting the following error when I call Rukuli::App#window

```
$ jruby main.rb
 
C:/jruby-9.0.0.0.pre1/lib/ruby/gems/shared/gems/rukuli-1.0.3/lib/rukuli/region.rb:30: warning: ambiguous Java methods found, using org.sikuli.script.Region(java.awt.Rectangle)
org/sikuli/script/Region.java:254:in `<init>': java.lang.NullPointerException
        from C:/jruby-9.0.0.0.pre1/lib/ruby/gems/shared/gems/rukuli-1.0.3/lib/rukuli/region.rb:30:in `initialize'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/gems/shared/gems/rukuli-1.0.3/lib/rukuli/app.rb:30:in `window'
        from main.rb:10:in `__script__'
        from main.rb:10:in `__script__'
```

Here's whats in main.rb:

```ruby
# main.rb
CURRENT_DIR = File.expand_path(File.dirname(__FILE__))
ENV['SIKULIX_HOME'] = "#{CURRENT_DIR}/sikuli-java.jar"
 
require 'java'
require 'rukuli'
 
app = Rukuli::App.new 'Notepad'
app.focus
 
app.window.click 10, 10
```

In this example, everything seems to work (I see notepad open) except for the last line. Am I doing something wrong? Or could it be that [Rukuli::Region#initialize](https://github.com/andreanastacio/Rukuli/blob/master/lib/rukuli/region.rb#L28-L30) and/or [Rukuli::App#window](https://github.com/andreanastacio/Rukuli/blob/master/lib/rukuli/app.rb#L29-L31) should be different. I'm not familiar with how Sikuli works.

Thanks!

**Comment by andreanastacio** [comment]
Hi @jrab89,
First I need the Log, testing on my machine I got this messages
```
$ ruby test.rb
[log] App.focus TextEdit(0) #0
[log] openApp: "TextEdit"
/usr/local/rvm/gems/jruby-1.7.19/gems/rukuli-1.0.3/lib/rukuli/clickable.rb:287 warning: ambiguous Java methods found, using org.sikuli.script.Location(int,int)
[log] CLICK on L(294,106)@S(0)[0,0 1280x800]
```

And a I need more information about your OS, what version of windows you're running?

**Comment by Ricardonacif** [comment]
Same here. Did anyone find out?

**Comment by andreanastacio** [comment]
@Ricardonacif Do you can send me the log?

**Comment by Ricardonacif** [comment]
Not sure what I did, but I could fix it :dancers:

**Comment by ndrluis** [comment]
@Ricardonacif @jrab89 ping
