### ISSUE TITLE
Is there anyway of seting the vision parameter?

### ISSUE THREAD

**Issue by Ricardonacif** [ndrluis/Rukuli#22]
Hey guys,

Is there anyway of setting the Vision.setParameter to a lower value? It decreases the quality of assertions on image but it speeds up a bit.

http://doc.sikuli.org/javadoc/org/sikuli/script/natives/Vision.html#setParameter(java.lang.String, float)

Thanks,

**Comment by Ricardonacif** [comment]
@andreanastacio do you know if it's possible?

**Comment by andreanastacio** [comment]
It's possible, if you want to contribute you can implement this feature on config class https://github.com/andreanastacio/Rukuli/blob/master/lib/rukuli/config.rb.

**Comment by Ricardonacif** [comment]
Will take a look at it! Thanks

**Comment by ndrluis** [comment]
@Ricardonacif ping

**Comment by Ricardonacif** [comment]
Hey @ndrluis I didn't have time to look at that and also the project was canceled :( Should I close this issue?
